DROP TABLE GOODS CASCADE CONSTRAINT;
DROP TABLE GOODS1 CASCADE CONSTRAINT;
DROP SEQUENCE GOODS_SEQ;

CREATE SEQUENCE GOODS_SEQ
INCREMENT BY 1
START WITH 1
MINVALUE 0 
MAXVALUE 9999 
NOCYCLE
NOCACHE

CREATE TABLE GOODS(

    GOODS_NO NUMBER PRIMARY KEY,
    MEMBER_ID VARCHAR2(50) NOT NULL,
    GOODS_TITLE VARCHAR2(100) NOT NULL UNIQUE,
    GOODS_MAIN_PHOTO VARCHAR2(1000) NOT NULL,
    GOODS_PRICE NUMBER NOT NULL,
    GOODS_QUANTITY NUMBER NOT NULL,
    GOODS_CONTENT VARCHAR2(4000) NOT NULL,
    GOODS_REGDATE DATE DEFAULT(SYSDATE) NOT NULL,
    CONSTRAINT GOODS_FK_MEMBER_ID FOREIGN KEY(MEMBER_ID) REFERENCES MEMBER(MEMBER_ID)
    ON DELETE CASCADE
);
--테이블정의서에서 GOODS_READCOUNT : 조회수 안 넣었습니다.

DELETE FROM GOODS;
 
SELECT * FROM GOODS;

INSERT INTO GOODS
VALUES(1,'ID','TEST입니다','썸네일','500','2','내용물',SYSDATE);

INSERT INTO GOODS
VALUES(GOODS_SEQ.NEXTVAL,'asdf','TEST2입니다','메인사진','600','3','내용물임',SYSDATE);

 	SELECT GOODS_NO, MEMBER_ID, GOODS_TITLE, GOODS_MAIN_PHOTO, GOODS_PRICE, GOODS_QUANTITY, 
  	GOODS_CONTENT, GOODS_REGDATE
  	FROM GOODS;
delete  from goods;

SELECT * FROM GOODS_SEQ;

