DROP TABLE KIND CASCADE CONSTRAINT;
DROP SEQUENCE KIND_SEQ;

CREATE SEQUENCE KIND_SEQ
INCREMENT BY 1
START WITH 1
MINVALUE 0 
MAXVALUE 9999 
NOCYCLE
NOCACHE


CREATE TABLE KIND(
	CATE_KIND_NO NUMBER PRIMARY KEY,
	CATE_KIND_NAME VARCHAR2(200) NOT NULL
);

INSERT INTO KIND VALUES(KIND_SEQ.NEXTVAL,'한식');
INSERT INTO KIND VALUES(KIND_SEQ.NEXTVAL,'일식');
INSERT INTO KIND VALUES(KIND_SEQ.NEXTVAL,'중식');
INSERT INTO KIND VALUES(KIND_SEQ.NEXTVAL,'양식');
INSERT INTO KIND VALUES(KIND_SEQ.NEXTVAL,'분식');
INSERT INTO KIND VALUES(KIND_SEQ.NEXTVAL,'간식');

SELECT * FROM KIND;

