DROP TABLE RECIPERE;
DROP TABLE RECIPERE CASCADE CONSTRAINTS;

CREATE SEQUENCE RECIPERE_SEQ
INCREMENT BY 1
START WITH 1
MINVALUE 0 
MAXVALUE 9999 
NOCYCLE
NOCACHE

CREATE TABLE RECIPERE(
RECIPE_RE_NO NUMBER PRIMARY KEY,
RECIPE_NO NUMBER NOT NULL,
RECIPE_RE_CONTENT VARCHAR2(50) NOT NULL,
RECIPE_RE_REGDATE DATE DEFAULT SYSDATE NOT NULL,
RECIPE_RE_GROUPNO NUMBER DEFAULT 1 NOT NULL,
RECIPE_RE_SEQ NUMBER  DEFAULT 1 UNIQUE NOT NULL,
RECIPE_RE_TITLETAB NUMBER NOT NULL,
MEMBER_ID VARCHAR2(20) NOT NULL,
CONSTRAINT RECIPERE_FK_RECIPE_NO FOREIGN KEY(RECIPE_NO) REFERENCES RECIPE(RECIPE_NO)
ON DELETE CASCADE,
CONSTRAINT RECIPERE_FK_MEMBER_ID FOREIGN KEY(MEMBER_ID) REFERENCES MEMBER(MEMBER_ID)
ON DELETE CASCADE
);

SELECT * FROM RECIPERE

DELETE FROM RECIPE