DROP SEQUENCE CALSEQ;
DROP TABLE CALBOARD;

CREATE SEQUENCE CALSEQ;
CREATE TABLE CALBOARD(
	SEQ NUMBER PRIMARY KEY,
	ID VARCHAR2(500) NOT NULL,
	TITLE VARCHAR2(2000) NOT NULL,
	CONTENT VARCHAR2(4000) NOT NULL,
	MDATE VARCHAR2(12) NOT NULL,--일정날짜
	REGDATE DATE NOT NULL
);

SELECT SEQ, ID, TITLE, CONTENT, MDATE, REGDATE 
FROM CALBOARD;

--ROW_NUMBER(): 숫자 붙혀주는 역할 중복된 값이 있더래도 다른숫자를 붙혀줌
-- @로 GROUP BY 해서, GROUP별 ROWNUM을 생성해줌
SELECT RN, SEQ, ID, TITLE, CONTENT, MDATE, REGDATE 
FROM 
(SELECT (ROW_NUMBER() OVER(PARTITION BY SUBSTR(MDATE,1,8) ORDER BY MDATE)) RN,
SEQ,
ID,
TITLE,
CONTENT,
MDATE,
REGDATE
FROM CALBOARD
WHERE ID = 'kh'
AND SUBSTR(MDATE, 1,6) = '202007')
WHERE RN BETWEEN 1 AND 3;	